/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.controllers.ReimbursementController;
import com.revature.controllers.UserController;
import com.revature.dao.IReimbursementDao;
import com.revature.dao.IUserDao;
import com.revature.dao.ReimbursementDaoJDBC;
import com.revature.dao.UserDaoJDBC;
import com.revature.services.ReimbursementService;
import com.revature.services.UserService;
import io.javalin.Javalin;

import static io.javalin.apibuilder.ApiBuilder.*;

public class Driver {

    public static void main(String[] args) {
        IUserDao uDao = new UserDaoJDBC();
        UserService uServ = new UserService(uDao);
        UserController uCon = new UserController(uServ);

        IReimbursementDao rDao = new ReimbursementDaoJDBC();
        ReimbursementService rServ = new ReimbursementService(rDao);
        ReimbursementController rCon = new ReimbursementController(rServ);

        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(()-> {
            path("user", () -> {
                post("/login", uCon.handleLogin);
                post("/logout", uCon.handleLogout);
                put("/update-account", uCon.handleUpdateAccountInformation);
            });

            path("manager", () -> {
                get("/view-employees", uCon.handleViewAllEmployees);
                post("/approve", rCon.handleApproveReimbursement);
                post("/deny", rCon.handleDenyReimbursement);
            });

            path("reimbursement", () -> {
                post("/create", rCon.handleCreateReimbursement);
                delete("/{id}", rCon.handleDeleteReimbursement);
            });
        });

        server.start(8080);

    }
}
